export const ACTIONS = {
    INITIALSTATE: "initialState",
    SELECTEDROW: "selectedRow",
    CREATESELECTEDROWCOPY: "CreateSelectedRowCopy",
    CONFIRMDELETE: "confirmdelete",
    CONFIRMINSERT: "confirminsert",
    CONFIRMUPDATE: "confirmupdate",
    UPDATEROW: "updateRow",
    REJECTCHANGES: "rejectChanges",
    COMMITROW: "commitRow",
    UPDATECHECKBOX: "updateCheckBox",
    SORT: "sort",
    FIRST: "first",
    LAST: "last",
    NEXT: "next",
    PREVIOUS: "Previous",
    GOTOPAGE: "goToPage",
    ITEMSPERPAGE: "itemsPerPage",
    SEARCHINPUTCHANGE: "SerachInputChange",
    SEARCH: "search",
    CREATE: "create",
    UPDATE: "update",
    DELETE: "delete",
    INSERT: "insert",
    CANCEL: "cancel",
    NOACTION: "NOACTION",
    SETUPDATEACTION: "setupdateaction",
    RETURNSTATE: "returnstate"
  };
  