export const ACTIONS = {
    UPDATEPROPS: 'updateprops',
    UPDATESELECTEDDATE: 'updateSelectedDate',
    SELECTEDROW: 'selectedRow',
    CREATESELECTEDROWCOPY: 'CreateSelectedRowCopy',
    CONFIRMDELETE: 'confirmdelete',
    CONFIRMINSERT: 'confirminsert',
    CONFIRMUPDATE: 'confirmupdate',
    UPDATEROW: 'updateRow',
    REJECTCHANGES: 'rejectChanges',
    UPDATECHECKBOX: 'updateCheckBox',
    SORT: 'sort',
    FIRST: 'first',
    LAST: 'last',
    NEXT: 'next',
    PREVIOUS: 'Previous',
    GOTOPAGE: 'goToPage',
    ITEMSPERPAGE: 'itemsPerPage',
    SEARCHINPUTCHANGE: 'SerachInputChange',
    SEARCH: 'search',
    CREATE: 'create',
    UPDATE: 'update',
    DELETE: 'delete',
    INSERT: 'insert',
    CANCEL: 'cancel',
    NOACTION: 'NOACTION',
    RETURNSTATE: 'returnstate',
}
