name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: creates output
        with:
          source-directory: "coverage"
          destination-github-username: "sajrashid"
          destination-repository-name: "docsSite"
          user-email: sajid.rashid@live.co.uk
          user_name: "sajrashid"
          commit_message: "copy latest code coverage folder"
          target-branch: master
